brew install --cask google-chrome
brew install --cask 1password
brew install --cask firefox
brew install --cask arc
brew install --cask slack
brew install --cask tableplus
brew install --cask fork
brew install --cask transmit
brew install --cask jetbrains-toolbox
brew install --cask phpstorm
brew install --cask visual-studio-code
brew install --cask hyper
brew install --cask notion-calendar
brew install --cask mimestream
brew install --cask basecamp
brew install --cask herd
brew install --cask discord
brew install --cask figma
